import "./globals.css";
import { Inter } from "next/font/google";
import HeaderLanding from "./components/header-landing";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-950 h-screen`}>
        <HeaderLanding />
        {children}
      </body>
    </html>
  );
}
